import type { ASSStyle } from "./ass";

const SERMON_BASE: ASSStyle = {
  name: "Sermon", fontname: "Arial", fontsize: 54,
  primaryColor: "&H00FFFFFF&", secondaryColor: "&H00FFFFFF&",
  outlineColor: "&H00181818&", shadowColor: "&H80000000&",
  bold: 1, italic: 0, outline: 3, shadow: 2, alignment: 2,
  marginL: 60, marginR: 60, marginV: 100, encoding: 1,
};

export const SERMON_CAPTION_STYLES: Record<string, ASSStyle & { animationClass?: string }> = {
  scripture: { ...SERMON_BASE, name: "Scripture", primaryColor: "&H0037D4F4&", borderStyle: 3, outline: 12 },
  testimony: { ...SERMON_BASE, name: "Testimony", fontname: "Chalkboard", primaryColor: "&H00C5E4FF&", outlineColor: "&H002B3449&", bold: 0 },
  "altar-call": { ...SERMON_BASE, name: "AltarCall", fontname: "Arial Black", outlineColor: "&H002525DC&", outline: 5, animationClass: "animate-pulse" },
};

export interface Template {
  id: string;
  name: string;
  desc: string;
  category: "story" | "conversation" | "quiz" | "reaction" | "educational" | "ministry";
  icon: string;
  defaults: Record<string, any>;
  fields: TemplateField[];
}

export interface TemplateField {
  key: string;
  label: string;
  type: "text" | "textarea" | "select" | "toggle" | "slider";
  placeholder?: string;
  options?: { value: string; label: string }[];
  default?: any;
  min?: number;
  max?: number;
  step?: number;
}

export const TEMPLATES: Template[] = [
  {
    id: "reddit_story",
    name: "Reddit Story",
    desc: "Reddit post with gameplay background + AI voiceover",
    category: "story",
    icon: "📱",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: false,
      captionStyle: "bold_pop",
      voice: "en-US-GuyNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "redditUrl",
        label: "Reddit URL",
        type: "text",
        placeholder: "https://reddit.com/r/...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-GuyNeural", label: "Guy (Male)" },
          { value: "en-US-AndrewNeural", label: "Andrew (Male)" },
          { value: "en-US-BrianNeural", label: "Brian (Male)" },
          { value: "en-US-AriaNeural", label: "Aria (Female)" },
          { value: "en-US-AvaNeural", label: "Ava (Female)" },
        ],
        default: "en-US-GuyNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          // Traditional ASS styles
          { value: "bold_pop", label: "Bold Pop (classic)" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "zoom", label: "Zoom" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "colorful", label: "Colorful" },
          
          // Viral styles (MrBeast, Hormozi, etc.)
          { value: "viral_mrbeast", label: "🔥 MrBeast (yellow pop)" },
          { value: "viral_hormozi", label: "💼 Hormozi (cyan bold)" },
          { value: "viral_karaoke", label: "🎤 Karaoke (color wipe)" },
          { value: "viral_minimal", label: "✨ Minimal (clean scale)" },
          { value: "viral_classic", label: "⚡ Classic (viral yellow)" },
          
          // Scattered word styles (aesthetic edits)
          { value: "scattered_clean", label: "🎨 Scattered - Clean" },
          { value: "scattered_neon", label: "🎮 Scattered - Neon" },
          { value: "scattered_pastel", label: "🌸 Scattered - Pastel" },
          { value: "scattered_bold", label: "💥 Scattered - Bold" },
          { value: "scattered_handwritten", label: "✍️ Scattered - Handwritten" },
          
          { value: "none", label: "No captions" },
        ],
        default: "viral_mrbeast",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "ai_story",
    name: "AI Story",
    desc: "AI-generated story with dramatic captions",
    category: "story",
    icon: "✨",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "word_by_word",
      voice: "en-US-ChristopherNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Story Text",
        type: "textarea",
        placeholder: "Write your story or paste a script...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          {
            value: "en-US-ChristopherNeural",
            label: "Christopher (Male, Authority)",
          },
          { value: "en-US-GuyNeural", label: "Guy (Male, Casual)" },
          { value: "en-US-AvaNeural", label: "Ava (Female, Friendly)" },
          { value: "en-US-EmmaNeural", label: "Emma (Female, Cheerful)" },
        ],
        default: "en-US-ChristopherNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "zoom", label: "Zoom" },
          { value: "shake", label: "Shake" },
          { value: "colorful", label: "Colorful" },
          { value: "glow", label: "Glow" },
          { value: "neon", label: "Neon" },
          { value: "minimal", label: "Minimal" },
        ],
        default: "word_by_word",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "fake_text",
    name: "Fake Text",
    desc: "iMessage-style text conversation",
    category: "conversation",
    icon: "💬",
    defaults: {
      type: "fake_text",
      fontSize: 32,
      senderName: "Contact",
    },
    fields: [
      {
        key: "senderName",
        label: "Contact Name",
        type: "text",
        placeholder: "Contact name",
        default: "Contact",
      },
      {
        key: "messages",
        label: "Messages (Me: / Them: format)",
        type: "textarea",
        placeholder: "Me: Hey!\nThem: What's up?\nMe: Not much",
      },
    ],
  },
  {
    id: "split_screen",
    name: "Split Screen",
    desc: "Main video + gameplay background side by side",
    category: "reaction",
    icon: "🎬",
    defaults: {
      type: "split_screen",
      bgPosition: "left",
    },
    fields: [
      {
        key: "url",
        label: "Video URL",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "bgPosition",
        label: "Gameplay Position",
        type: "select",
        options: [
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
          { value: "top", label: "Top" },
          { value: "bottom", label: "Bottom" },
        ],
        default: "left",
      },
    ],
  },
  {
    id: "quiz",
    name: "Quiz / Trivia",
    desc: "Question with countdown and answer reveal",
    category: "quiz",
    icon: "🧠",
    defaults: {
      type: "story",
      voiceover: false,
      bgVideo: false,
      bgMusic: false,
      captionStyle: "bold_pop",
    },
    fields: [
      {
        key: "question",
        label: "Question",
        type: "text",
        placeholder: "What is the capital of France?",
      },
      { key: "answer", label: "Answer", type: "text", placeholder: "Paris" },
      {
        key: "options",
        label: "Options (comma-separated)",
        type: "text",
        placeholder: "Paris, London, Berlin, Madrid",
      },
      {
        key: "timer",
        label: "Countdown (seconds)",
        type: "select",
        options: [
          { value: "3", label: "3 seconds" },
          { value: "5", label: "5 seconds" },
          { value: "7", label: "7 seconds" },
          { value: "10", label: "10 seconds" },
        ],
        default: "5",
      },
    ],
  },
  {
    id: "scary_story",
    name: "Scary Story",
    desc: "Horror story with dark theme and eerie voice",
    category: "story",
    icon: "👻",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: false,
      bgMusic: false,
      captionStyle: "minimal",
      voice: "en-US-ChristopherNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Scary Story",
        type: "textarea",
        placeholder: "Write your horror story...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-ChristopherNeural", label: "Christopher (Deep)" },
          { value: "en-US-BrianNeural", label: "Brian (Soft)" },
        ],
        default: "en-US-ChristopherNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "minimal", label: "Minimal" },
          { value: "bold_pop", label: "Bold Pop" },
          { value: "glow", label: "Glow" },
          { value: "neon", label: "Neon" },
          { value: "typewriter", label: "Typewriter" },
        ],
        default: "minimal",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "advice",
    name: "Life Advice",
    desc: "Motivational quote or life lesson with dramatic captions",
    category: "educational",
    icon: "💡",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: false,
      captionStyle: "colorful",
      voice: "en-US-AvaNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Advice / Quote",
        type: "textarea",
        placeholder: "The only way to do great work is to love what you do...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-AvaNeural", label: "Ava (Female, Warm)" },
          { value: "en-US-AndrewNeural", label: "Andrew (Male, Confident)" },
        ],
        default: "en-US-AvaNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "colorful", label: "Colorful" },
          { value: "bold_pop", label: "Bold Pop" },
          { value: "bounce", label: "Bounce" },
          { value: "zoom", label: "Zoom" },
          { value: "word_by_word", label: "Word by Word" },
        ],
        default: "colorful",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "pov_story",
    name: "POV Story",
    desc: "First-person perspective story with you-centric captions",
    category: "story",
    icon: "🎥",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "bold_pop",
      voice: "en-US-GuyNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "POV Story",
        type: "textarea",
        placeholder:
          "POV: You walk into a room and notice something strange...",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-GuyNeural", label: "Guy (Casual)" },
          { value: "en-US-AvaNeural", label: "Ava (Friendly)" },
        ],
        default: "en-US-GuyNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "bounce", label: "Bounce" },
          { value: "zoom", label: "Zoom" },
          { value: "typewriter", label: "Typewriter" },
          { value: "word_by_word", label: "Word by Word" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "auto_clip",
    name: "Auto Clip",
    desc: "Paste a YouTube URL → auto-detect genre + best moments → extract clips",
    category: "story",
    icon: "✂️",
    defaults: {
      type: "story",
      clipCount: 5,
      minDuration: 15,
      maxDuration: 60,
      language: "en",
      voiceover: false,
      bgVideo: false,
      bgMusic: false,
      captionStyle: "bold_pop",
      platform: "9:16",
      quality: "standard",
      transition: "none",
      smartZoom: false,
      voiceVolume: 1.0,
      musicVolume: 0.15,
      autoGenre: true,
      selectedGenres: [],
    },
    fields: [
      {
        key: "url",
        label: "YouTube / TikTok URL or Upload MP4",
        type: "text",
        placeholder: "https://youtube.com/watch?v=... or upload mp4",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "autoGenre",
        label: "Auto-Detect Genre",
        type: "toggle",
        default: true,
      },
      {
        key: "selectedGenres",
        label: "Select Genres (if not auto-detect)",
        type: "text",
        placeholder: "sermon, church_promo, testimony, worship, teaching, devotional, youth, kids, event",
        default: [],
      },
      {
        key: "clipCount",
        label: "Number of Clips",
        type: "slider",
        min: 1,
        max: 50,
        step: 1,
        default: 5,
      },
      {
        key: "minDuration",
        label: "Min Clip Duration (sec)",
        type: "slider",
        min: 5,
        max: 30,
        step: 5,
        default: 15,
      },
      {
        key: "maxDuration",
        label: "Max Clip Duration (sec)",
        type: "slider",
        min: 30,
        max: 120,
        step: 10,
        default: 60,
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "holy_glow", label: "Holy Glow" },
          { value: "cross_bold", label: "Cross Bold" },
          { value: "worship_purple", label: "Worship Purple" },
          { value: "scripture_serif", label: "Scripture Serif" },
          { value: "fire_revival", label: "Fire Revival" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "colorful", label: "Colorful" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "smartTitle",
        label: "AI Generate Titles",
        type: "toggle",
        default: true,
      },
      {
        key: "titleOverride",
        label: "Custom Title (overrides AI)",
        type: "text",
        placeholder: "Leave empty for AI-generated",
      },
    ],
  },
  {
    id: "sermon_clip",
    name: "Sermon Clip (Christian Agency Template)",
    desc: "YouTube sermon → auto-detect highlights → captioned clips with hook intro and Christian styling",
    category: "story",
    icon: "⛪",
    defaults: {
      type: "sermon_clip",
      clipCount: 5,
      minDuration: 15,
      maxDuration: 60,
      language: "en",
      voiceover: false,
      bgVideo: true,
      bgMusic: false,
      captionStyle: "holy_glow",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
      hookIntro: "This sermon changed everything...",
      silenceRemoval: false,
    },
    fields: [
      {
        key: "url",
        label: "YouTube Sermon URL",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "hookIntro",
        label: "Hook Intro Text",
        type: "text",
        placeholder: "Watch this...",
      },
      {
        key: "clipCount",
        label: "Number of Clips",
        type: "slider",
        min: 1,
        max: 50,
        step: 1,
        default: 5,
      },
      {
        key: "minDuration",
        label: "Min Clip Duration (sec)",
        type: "slider",
        min: 5,
        max: 30,
        step: 5,
        default: 15,
      },
      {
        key: "maxDuration",
        label: "Max Clip Duration (sec)",
        type: "slider",
        min: 30,
        max: 120,
        step: 10,
        default: 60,
      },
      {
        key: "scriptureReference", label: "Scripture Reference", type: "text", placeholder: "John 3:16",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "scripture", label: "Scripture (gold with reference)" },
          { value: "testimony", label: "Testimony (warm handwritten)" },
          { value: "altar-call", label: "Altar Call (red and white pulse)" },
          { value: "holy_glow", label: "Holy Glow (reverent)" },
          { value: "cross_bold", label: "Cross Bold (strong)" },
          { value: "worship_purple", label: "Worship Purple (praise)" },
          { value: "scripture_serif", label: "Scripture Serif (traditional)" },
          { value: "fire_revival", label: "Fire Revival (passion)" },
          { value: "bold_pop", label: "Bold Pop" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "colorful", label: "Colorful" },
        ],
        default: "holy_glow",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Sermon Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
      {
        key: "silenceRemoval",
        label: "Remove Silence",
        type: "toggle",
        default: false,
      },
    ],
  },
  {
    id: "sermon_quote",
    name: "Sermon Quote",
    desc: "Single powerful quote with dramatic text reveal",
    category: "story",
    icon: "📖",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "zoom",
      voice: "en-US-ChristopherNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.2,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Quote",
        type: "textarea",
        placeholder:
          '"For God so loved the world that he gave his one and only Son..."',
      },
      {
        key: "attribution",
        label: "Attribution (optional)",
        type: "text",
        placeholder: "John 3:16",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          {
            value: "en-US-ChristopherNeural",
            label: "Christopher (Authority)",
          },
          { value: "en-US-GuyNeural", label: "Guy (Warm)" },
          { value: "en-US-AvaNeural", label: "Ava (Gentle)" },
        ],
        default: "en-US-ChristopherNeural",
      },
      {
        key: "captionStyle",
        label: "Text Style",
        type: "select",
        options: [
          { value: "zoom", label: "Zoom Reveal" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "glow", label: "Glow" },
          { value: "neon", label: "Neon" },
          { value: "bold_pop", label: "Bold Pop" },
        ],
        default: "zoom",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.2,
      },
    ],
  },
  // ─── Ministry-specific templates ───
  {
    id: "sermon_teaching",
    name: "Sermon Teaching Clip",
    desc: "Extract key teaching point → scripture reference + application",
    category: "ministry",
    icon: "📖",
    defaults: {
      type: "teaching_clip",
      clipCount: 3,
      minDuration: 20,
      maxDuration: 60,
      captionStyle: "holy_glow",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.12,
      hookIntro: "Here's what Scripture says about...",
      bgMusic: "worship",
      scriptureOverlay: true,
    },
    fields: [
      { key: "url", label: "Sermon URL", type: "text", placeholder: "https://youtube.com/watch?v=..." },
      { key: "scripture", label: "Bible Reference", type: "text", placeholder: "Matthew 11:28" },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "holy_glow", label: "Holy Glow (reverent)" },
          { value: "cross_bold", label: "Cross Bold (strong)" },
          { value: "scripture_serif", label: "Scripture Serif (traditional)" },
        ],
        default: "holy_glow",
      },
    ],
  },
  {
    id: "worship_moment",
    name: "Worship Moment Clip",
    desc: "Worship performance → lyrical highlight + call to engage",
    category: "ministry",
    icon: "🎤",
    defaults: {
      type: "worship_clip",
      clipCount: 1,
      minDuration: 30,
      maxDuration: 60,
      captionStyle: "worship_purple",
      platform: "9:16",
      quality: "high",
      transition: "none",
      voiceVolume: 0.5,
      musicVolume: 0.5,
      hookIntro: "This song will bless you...",
      bgMusic: "worship",
    },
    fields: [
      { key: "url", label: "Worship Performance URL", type: "text" },
      { key: "songTitle", label: "Song Title", type: "text", placeholder: "What a Beautiful Name" },
      { key: "artist", label: "Artist/Band", type: "text" },
    ],
  },
  {
    id: "pastor_short",
    name: "Pastor Short Clip",
    desc: "Pastor's quote or insight → quick encouragement + church branding",
    category: "ministry",
    icon: "👨‍💼",
    defaults: {
      type: "quote",
      clipCount: 1,
      minDuration: 15,
      maxDuration: 45,
      captionStyle: "cross_bold",
      platform: "9:16",
      quality: "standard",
      transition: "none",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.15,
      hookIntro: "Our pastor said it best...",
      bgMusic: "ambient",
    },
    fields: [
      { key: "url", label: "Sermon or Message URL", type: "text" },
      { key: "pastor", label: "Pastor Name", type: "text", placeholder: "Pastor Mike" },
      { key: "churchName", label: "Church Name", type: "text", placeholder: "Grace Community Church" },
    ],
  },
  {
    name: "Testimony",
    desc: "Personal testimony with emotional captions + dramatic music",
    category: "story",
    icon: "🕊️",
    defaults: {
      type: "story",
      voiceover: true,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "word_by_word",
      voice: "en-US-AvaNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.25,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "script",
        label: "Testimony Story",
        type: "textarea",
        placeholder:
          "I was lost for years. I struggled with addiction, depression, and hopelessness...",
      },
      {
        key: "speakerName",
        label: "Speaker Name (optional)",
        type: "text",
        placeholder: "Sarah's Testimony",
      },
      {
        key: "voice",
        label: "Voice",
        type: "select",
        options: [
          { value: "en-US-AvaNeural", label: "Ava (Female, Warm)" },
          { value: "en-US-EmmaNeural", label: "Emma (Female, Gentle)" },
          { value: "en-US-GuyNeural", label: "Guy (Male, Calm)" },
          { value: "en-US-BrianNeural", label: "Brian (Male, Soft)" },
        ],
        default: "en-US-AvaNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "word_by_word", label: "Word by Word" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bold_pop", label: "Bold Pop" },
          { value: "colorful", label: "Colorful" },
          { value: "glow", label: "Glow" },
        ],
        default: "word_by_word",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.25,
      },
    ],
  },
  {
    id: "podcast_clip",
    name: "Podcast Clip",
    desc: "YouTube podcast → auto-detect highlights → captioned clips",
    category: "story",
    icon: "🎙️",
    defaults: {
      type: "podcast_clip",
      clipCount: 5,
      minDuration: 15,
      maxDuration: 60,
      language: "en",
      voiceover: false,
      bgVideo: true,
      bgMusic: false,
      captionStyle: "bold_pop",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.1,
      silenceRemoval: false,
    },
    fields: [
      {
        key: "url",
        label: "YouTube Podcast URL",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "clipCount",
        label: "Number of Clips",
        type: "slider",
        min: 1,
        max: 50,
        step: 1,
        default: 5,
      },
      {
        key: "minDuration",
        label: "Min Clip Duration (sec)",
        type: "slider",
        min: 5,
        max: 30,
        step: 5,
        default: 15,
      },
      {
        key: "maxDuration",
        label: "Max Clip Duration (sec)",
        type: "slider",
        min: 30,
        max: 120,
        step: 10,
        default: 60,
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "word_by_word", label: "Word by Word" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "colorful", label: "Colorful" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "transition",
        label: "Scene Transition",
        type: "select",
        options: [
          { value: "none", label: "None" },
          { value: "crossfade", label: "Crossfade" },
          { value: "zoom_cut", label: "Zoom Cut" },
        ],
        default: "crossfade",
      },
      {
        key: "smartZoom",
        label: "Smart Zoom (Face Tracking)",
        type: "toggle",
        default: true,
      },
      {
        key: "voiceVolume",
        label: "Audio Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.1,
      },
      {
        key: "silenceRemoval",
        label: "Remove Silence",
        type: "toggle",
        default: false,
      },
    ],
  },
  {
    id: "reaction",
    name: "Reaction",
    desc: "React to a video — picture-in-picture with commentary",
    category: "reaction",
    icon: "😲",
    defaults: {
      type: "reaction",
      pipPosition: "bottom-right",
      pipSize: 0.3,
      bgVideo: false,
      bgMusic: false,
      captionStyle: "bold_pop",
      platform: "9:16",
      quality: "standard",
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "mainUrl",
        label: "Main Video URL (what you're reacting to)",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "reactionUrl",
        label: "Reaction Video URL (your face cam)",
        type: "text",
        placeholder: "https://youtube.com/watch?v=... or local file",
      },
      {
        key: "pipPosition",
        label: "Your Camera Position",
        type: "select",
        options: [
          { value: "bottom-right", label: "Bottom Right" },
          { value: "bottom-left", label: "Bottom Left" },
          { value: "top-right", label: "Top Right" },
          { value: "top-left", label: "Top Left" },
        ],
        default: "bottom-right",
      },
      {
        key: "pipSize",
        label: "Camera Size",
        type: "slider",
        min: 0.15,
        max: 0.5,
        step: 0.05,
        default: 0.3,
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "typewriter", label: "Typewriter" },
          { value: "bounce", label: "Bounce" },
          { value: "word_by_word", label: "Word by Word" },
        ],
        default: "bold_pop",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
    ],
  },
  {
    id: "top_list",
    name: "Top 5 / List",
    desc: 'Countdown list with dramatic reveals — "Top 5 reasons..."',
    category: "educational",
    icon: "🔢",
    defaults: {
      type: "top_list",
      voiceover: false,
      bgVideo: true,
      bgMusic: true,
      captionStyle: "bold_pop",
      voice: "en-US-GuyNeural",
      platform: "9:16",
      quality: "standard",
      transition: "crossfade",
      smartZoom: false,
      voiceVolume: 1.0,
      musicVolume: 0.15,
      revealDuration: 3,
    },
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "title",
        label: "List Title",
        type: "text",
        placeholder: "Top 5 Signs You're Growing Closer to God",
      },
      {
        key: "items",
        label: "List Items (one per line)",
        type: "textarea",
        placeholder:
          "You pray without being asked\nYou forgive faster\nYou feel peace in chaos\nYou crave Scripture\nYour relationships improve",
      },
      {
        key: "voice",
        label: "Voice (for narration)",
        type: "select",
        options: [
          { value: "en-US-GuyNeural", label: "Guy (Casual)" },
          {
            value: "en-US-ChristopherNeural",
            label: "Christopher (Authority)",
          },
          { value: "en-US-AvaNeural", label: "Ava (Friendly)" },
        ],
        default: "en-US-GuyNeural",
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "bold_pop", label: "Bold Pop" },
          { value: "zoom", label: "Zoom Reveal" },
          { value: "bounce", label: "Bounce" },
          { value: "typewriter", label: "Typewriter" },
          { value: "colorful", label: "Colorful" },
        ],
        default: "bold_pop",
      },
      {
        key: "revealDuration",
        label: "Seconds per Item",
        type: "slider",
        min: 2,
        max: 8,
        step: 1,
        default: 3,
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
      {
        key: "voiceVolume",
        label: "Voice Volume",
        type: "slider",
        min: 0,
        max: 2,
        step: 0.1,
        default: 1.0,
      },
      {
        key: "musicVolume",
        label: "Music Volume",
        type: "slider",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.15,
      },
    ],
  },
  {
    id: "standup_comedy",
    name: "Standup Comedy",
    desc: "Comedy special → highlight clips with punch-up captions, laugh-reactive timing, and audience-reactive zoom cuts",
    category: "reaction",
    icon: "🎤",
    defaults: {
      type: "story",
      bgVideo: false,
      bgMusic: true,
      captionStyle: "bold_pop",
      platform: "9:16",
      quality: "standard",
      transition: "zoom_cut",
      smartZoom: true,
      voiceVolume: 1.0,
      musicVolume: 0.2,
      // Comedy-specific defaults
      extendForLaughter: true,
      zoomOnLaughter: true,
      punchUpCaptions: true,
      titleStyle: "bold_pop",
      hookIntro: "Wait... until you hear this",
      clipCount: 5,
      minDuration: 30,
      maxDuration: 90,
    },
    fields: [
      {
        key: "url",
        label: "YouTube URL (or upload mp4 below)",
        type: "text",
        placeholder: "https://youtube.com/watch?v=...",
      },
      {
        key: "clipCount",
        label: "Number of Clips",
        type: "slider",
        min: 1,
        max: 50,
        step: 1,
        default: 5,
      },
      {
        key: "minDuration",
        label: "Min Clip Length (sec)",
        type: "slider",
        min: 15,
        max: 60,
        step: 5,
        default: 30,
      },
      {
        key: "maxDuration",
        label: "Max Clip Length (sec)",
        type: "slider",
        min: 30,
        max: 180,
        step: 10,
        default: 90,
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          // Traditional ASS styles
          { value: "bold_pop", label: "Bold Pop (title + captions)" },
          { value: "colorful", label: "Colorful (vibrant)" },
          { value: "neon", label: "Neon (glowing)" },
          { value: "bounce", label: "Bounce (energetic)" },
          { value: "word_by_word", label: "Word-by-Word (synced)" },
          
          // Viral styles
          { value: "viral_mrbeast", label: "🔥 MrBeast (yellow pop)" },
          { value: "viral_hormozi", label: "💼 Hormozi (cyan bold)" },
          { value: "viral_classic", label: "⚡ Classic (viral yellow)" },
          
          // Scattered word styles (aesthetic edits)
          { value: "scattered_clean", label: "🎨 Scattered - Clean" },
          { value: "scattered_neon", label: "🎮 Scattered - Neon" },
          { value: "scattered_bold", label: "💥 Scattered - Bold" },
          
          { value: "none", label: "No captions" },
        ],
        default: "viral_mrbeast",
      },
      {
        key: "platform",
        label: "Platform Format",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok / Shorts / Reels (9:16)" },
          { value: "1:1", label: "Instagram Feed (1:1)" },
        ],
        default: "9:16",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p, fast)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, slow)" },
          { value: "ultra", label: "Ultra (4K, slow)" },
        ],
        default: "standard",
      },
    ],
  },
  
  // ═══ Music Edit ═══
  {
    id: "music-edit",
    name: "Music Edit",
    desc: "Auto-cut video clips to music beats (aesthetic edits, AMV, GMV)",
    category: "story",
    icon: "🎵",
    defaults: {
      platform: "9:16",
      quality: "high",
      captionStyle: "scattered_neon",
      cutDensity: "auto",
      minClipLength: 0.5,
      maxClipLength: 4,
      transitionStyle: "cut",
    },
    fields: [
      {
        key: "audioFile",
        label: "Music Track",
        type: "text",
        placeholder: "Upload music track URL or path",
      },
      {
        key: "sourceVideos",
        label: "Source Videos (comma-separated paths)",
        type: "textarea",
        placeholder: "/path/to/video1.mp4,/path/to/video2.mp4",
      },
      {
        key: "platform",
        label: "Platform Format",
        type: "select",
        options: [
          { value: "9:16", label: "TikTok/Shorts (9:16)" },
          { value: "1:1", label: "Instagram Square (1:1)" },
          { value: "16:9", label: "YouTube (16:9)" },
        ],
        default: "9:16",
      },
      {
        key: "cutDensity",
        label: "Cut Density",
        type: "select",
        options: [
          { value: "auto", label: "Auto (follows music energy)" },
          { value: "low", label: "Low (slow cuts)" },
          { value: "medium", label: "Medium" },
          { value: "high", label: "High (fast cuts)" },
        ],
        default: "auto",
      },
      {
        key: "minClipLength",
        label: "Min Clip Length (sec)",
        type: "slider",
        min: 0.25,
        max: 2,
        step: 0.25,
        default: 0.5,
      },
      {
        key: "maxClipLength",
        label: "Max Clip Length (sec)",
        type: "slider",
        min: 1,
        max: 10,
        step: 0.5,
        default: 4,
      },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "none", label: "No captions" },
          { value: "scattered_neon", label: "🎮 Scattered - Neon" },
          { value: "scattered_clean", label: "🎨 Scattered - Clean" },
          { value: "scattered_pastel", label: "🌸 Scattered - Pastel" },
          { value: "viral_mrbeast", label: "🔥 MrBeast" },
        ],
        default: "scattered_neon",
      },
      {
        key: "transitionStyle",
        label: "Transition Style",
        type: "select",
        options: [
          { value: "cut", label: "Hard Cut (instant)" },
          { value: "fade", label: "Fade (crossfade)" },
          { value: "dissolve", label: "Dissolve (blend)" },
          { value: "zoom_in", label: "Zoom In (circle crop)" },
          { value: "zoom_out", label: "Zoom Out (circle open)" },
          { value: "slide_left", label: "Slide Left" },
          { value: "slide_right", label: "Slide Right" },
        ],
        default: "cut",
      },
      {
        key: "quality",
        label: "Export Quality",
        type: "select",
        options: [
          { value: "draft", label: "Draft (720p)" },
          { value: "standard", label: "Standard (1080p)" },
          { value: "high", label: "High (1080p, CRF 18)" },
          { value: "ultra", label: "Ultra (4K)" },
        ],
        default: "high",
      },
    ],
  },
];

export function getTemplate(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: string): Template[] {
  return TEMPLATES.filter((t) => t.category === category);
}

export const CHRISTIAN_TEMPLATES: Template[] = [
  // 1. Sunday Sermon Highlights
  {
    id: "sermon_highlight",
    name: "Sunday Sermon Highlights",
    desc: "Extract 3-5 powerful moments from full sermon → vertical clips with scripture overlays",
    category: "ministry",
    icon: "⛪",
    defaults: {
      type: "sermon_clip",
      clipCount: 5,
      minDuration: 20,
      maxDuration: 60,
      captionStyle: "holy_glow",
      platform: "9:16",
      quality: "standard",
      bgMusic: "worship",
      scriptureOverlay: true,
      voiceVolume: 1.0,
      musicVolume: 0.12,
    },
    fields: [
      { key: "url", label: "Sermon YouTube URL", type: "text", placeholder: "https://youtube.com/watch?v=..." },
      { key: "sermonTitle", label: "Sermon Title", type: "text", placeholder: "The Power of Prayer" },
      { key: "pastor", label: "Pastor Name", type: "text", placeholder: "Pastor John Smith" },
      { key: "scripture", label: "Key Scriptures (comma-separated)", type: "text", placeholder: "John 3:16, Romans 8:28" },
      {
        key: "captionStyle",
        label: "Caption Style",
        type: "select",
        options: [
          { value: "holy_glow", label: "Holy Glow (reverent)" },
          { value: "cross_bold", label: "Cross Bold (strong)" },
          { value: "worship_purple", label: "Worship Purple (praise)" },
        ],
        default: "holy_glow",
      },
    ],
  },

  // 2. Testimony Short
  {
    id: "testimony_short",
    name: "Testimony Story",
    desc: "Personal testimony → emotional hook + transformation + call-to-action",
    category: "ministry",
    icon: "🙏",
    defaults: {
      type: "story",
      clipCount: 1,
      minDuration: 30,
      maxDuration: 90,
      captionStyle: "worship_purple",
      platform: "9:16",
      hookIntro: "My testimony will blow your mind...",
      bgMusic: "ambient",
      emotionDetection: true,
    },
    fields: [
      { key: "url", label: "Testimony Video URL or Upload", type: "text" },
      { key: "hookIntro", label: "Hook Text", type: "text", placeholder: "This changed my life..." },
      { key: "callToAction", label: "End CTA", type: "text", placeholder: "Share your testimony below!" },
    ],
  },

  // 3. Worship Lyric Video
  {
    id: "worship_lyrics",
    name: "Worship Lyrics Video",
    desc: "Worship song → synchronized animated lyrics with aesthetic background",
    category: "ministry",
    icon: "🎵",
    defaults: {
      type: "lyric_video",
      captionStyle: "worship_purple",
      platform: "9:16",
      quality: "high",
      bgVideo: "worship_abstract",
      textAnimation: "fade_in_out",
    },
    fields: [
      { key: "audioUrl", label: "Worship Song Audio", type: "text" },
      { key: "songTitle", label: "Song Title", type: "text" },
      { key: "artist", label: "Artist/Band", type: "text" },
      { key: "lyrics", label: "Lyrics (one line per box)", type: "textarea" },
    ],
  },

  // 4. Bible Verse Animation
  {
    id: "verse_animation",
    name: "Bible Verse Animation",
    desc: "Single scripture → cinematic background + elegant typography",
    category: "ministry",
    icon: "📖",
    defaults: {
      type: "verse_overlay",
      captionStyle: "scripture_serif",
      platform: "1:1",
      duration: 8,
      bgVideo: "nature_worship",
      textAnimation: "typewriter",
    },
    fields: [
      { key: "verse", label: "Bible Verse", type: "textarea", placeholder: "For God so loved the world..." },
      { key: "reference", label: "Reference", type: "text", placeholder: "John 3:16" },
      { key: "bgTheme", label: "Background", type: "select", options: [
        { value: "nature_worship", label: "Nature" },
        { value: "cross_sunset", label: "Cross at Sunset" },
        { value: "church_interior", label: "Church Interior" },
        { value: "abstract_light", label: "Abstract Light" },
      ]},
    ],
  },

  // 5. Prayer Request Callout
  {
    id: "prayer_request",
    name: "Prayer Request",
    desc: "Community prayer invitation → soft music + centered text",
    category: "ministry",
    icon: "🤲",
    defaults: {
      type: "text_overlay",
      captionStyle: "holy_glow",
      platform: "1:1",
      duration: 10,
      bgMusic: "ambient",
      bgVideo: "candle_prayer",
    },
    fields: [
      { key: "prayerText", label: "Prayer Request Text", type: "textarea", placeholder: "Praying for healing..." },
      { key: "churchName", label: "Church Name", type: "text" },
    ],
  },

  // 6. Weekly Devotional
  {
    id: "daily_devotional",
    name: "Daily/Weekly Devotional",
    desc: "Short teaching moment → verse + application + prayer",
    category: "ministry",
    icon: "☀️",
    defaults: {
      type: "devotional",
      clipCount: 1,
      minDuration: 45,
      maxDuration: 90,
      captionStyle: "cross_bold",
      platform: "9:16",
      scriptureOverlay: true,
    },
    fields: [
      { key: "url", label: "Devotional Video URL", type: "text" },
      { key: "title", label: "Devotional Title", type: "text", placeholder: "Monday Morning Encouragement" },
      { key: "scripture", label: "Key Verse", type: "text", placeholder: "Philippians 4:13" },
    ],
  },

  // 7. Altar Call / Salvation Invitation
  {
    id: "altar_call",
    name: "Altar Call / Salvation",
    desc: "Gospel presentation → powerful call to accept Christ",
    category: "ministry",
    icon: "✝️",
    defaults: {
      type: "sermon_clip",
      clipCount: 1,
      minDuration: 60,
      maxDuration: 120,
      captionStyle: "fire_revival",
      platform: "9:16",
      bgMusic: "soft_worship",
      emotionDetection: true,
    },
    fields: [
      { key: "url", label: "Sermon/Message URL", type: "text" },
      { key: "callToAction", label: "End CTA", type: "text", placeholder: "Accept Jesus today!" },
    ],
  },

  // 8. Kids Ministry Moment
  {
    id: "kids_ministry",
    name: "Kids Ministry Clip",
    desc: "Children's lesson → colorful, upbeat, short attention span friendly",
    category: "ministry",
    icon: "👶",
    defaults: {
      type: "kids_clip",
      clipCount: 3,
      minDuration: 15,
      maxDuration: 45,
      captionStyle: "colorful",
      platform: "9:16",
      bgMusic: "upbeat",
      transitions: "bounce",
    },
    fields: [
      { key: "url", label: "Kids Ministry Video URL", type: "text" },
      { key: "lessonTitle", label: "Lesson Title", type: "text", placeholder: "David and Goliath" },
    ],
  },

  // 9. Youth Group Hype
  {
    id: "youth_group",
    name: "Youth Group Hype",
    desc: "Youth ministry event → high energy, modern style, peer-focused",
    category: "ministry",
    icon: "🔥",
    defaults: {
      type: "youth_clip",
      clipCount: 5,
      minDuration: 10,
      maxDuration: 30,
      captionStyle: "fire_revival",
      platform: "9:16",
      bgMusic: "energetic",
      transitions: "fast",
      textSpeed: "fast",
    },
    fields: [
      { key: "url", label: "Youth Event Video", type: "text" },
      { key: "eventName", label: "Event Name", type: "text", placeholder: "Summer Camp 2026" },
    ],
  },

  // 10. Baptism Announcement
  {
    id: "baptism_announcement",
    name: "Baptism Announcement",
    desc: "Baptism celebration → joyful, celebratory, invitation to next baptism",
    category: "ministry",
    icon: "💧",
    defaults: {
      type: "celebration",
      clipCount: 1,
      minDuration: 20,
      maxDuration: 60,
      captionStyle: "worship_purple",
      platform: "9:16",
      bgMusic: "worship",
      transitions: "crossfade",
    },
    fields: [
      { key: "url", label: "Baptism Video", type: "text" },
      { key: "baptismDate", label: "Next Baptism Date", type: "text", placeholder: "Sunday, March 15" },
    ],
  },

  // 11. Mission Trip Recap
  {
    id: "mission_recap",
    name: "Mission Trip Recap",
    desc: "Mission/outreach highlights → impact stories + photos + call to support",
    category: "ministry",
    icon: "🌍",
    defaults: {
      type: "photo_montage",
      clipCount: 1,
      duration: 60,
      captionStyle: "cross_bold",
      platform: "16:9",
      bgMusic: "inspirational",
      transitions: "slide",
    },
    fields: [
      { key: "photos", label: "Mission Photos (upload or URLs)", type: "textarea" },
      { key: "missionLocation", label: "Location", type: "text", placeholder: "Guatemala" },
      { key: "impactStats", label: "Impact Numbers", type: "text", placeholder: "200 fed, 50 saved" },
    ],
  },

  // 12. Church Event Promo
  {
    id: "event_promo",
    name: "Church Event Promo",
    desc: "Upcoming event announcement → date, time, location, registration link",
    category: "ministry",
    icon: "📅",
    defaults: {
      type: "event_promo",
      clipCount: 1,
      duration: 15,
      captionStyle: "cross_bold",
      platform: "1:1",
      bgVideo: "church_exterior",
      textAnimation: "zoom",
    },
    fields: [
      { key: "eventName", label: "Event Name", type: "text", placeholder: "Easter Sunrise Service" },
      { key: "eventDate", label: "Date & Time", type: "text", placeholder: "Sunday, April 20 @ 6:00 AM" },
      { key: "location", label: "Location", type: "text", placeholder: "Main Sanctuary" },
      { key: "registerUrl", label: "Registration URL", type: "text" },
    ],
  },

  // 13. Pastor's Weekly Message
  {
    id: "pastor_weekly",
    name: "Pastor's Weekly Word",
    desc: "Short pastor greeting/encouragement → personal, conversational, builds trust",
    category: "ministry",
    icon: "👔",
    defaults: {
      type: "pastor_message",
      clipCount: 1,
      minDuration: 30,
      maxDuration: 90,
      captionStyle: "minimal",
      platform: "9:16",
      faceTracking: true,
      bgMusic: "soft_ambient",
    },
    fields: [
      { key: "url", label: "Pastor Video URL", type: "text" },
      { key: "pastor", label: "Pastor Name", type: "text" },
      { key: "messageTheme", label: "Message Theme", type: "text", placeholder: "Hope in Hard Times" },
    ],
  },

  // 14. Prophetic Word / Vision
  {
    id: "prophetic_word",
    name: "Prophetic Word",
    desc: "Prophetic message → reverent, powerful, scripture-backed",
    category: "ministry",
    icon: "⚡",
    defaults: {
      type: "prophetic",
      clipCount: 1,
      minDuration: 45,
      maxDuration: 120,
      captionStyle: "fire_revival",
      platform: "9:16",
      scriptureOverlay: true,
      bgMusic: "ambient",
      emotionDetection: true,
    },
    fields: [
      { key: "url", label: "Message Video URL", type: "text" },
      { key: "prophet", label: "Speaker Name", type: "text" },
      { key: "scripture", label: "Supporting Verses", type: "text" },
    ],
  },

  // 15. Christmas/Easter Special
  {
    id: "holiday_special",
    name: "Christmas/Easter Service",
    desc: "Holiday service highlights → celebration, invitation, share-worthy",
    category: "ministry",
    icon: "🎄",
    defaults: {
      type: "sermon_clip",
      clipCount: 5,
      minDuration: 20,
      maxDuration: 60,
      captionStyle: "holy_glow",
      platform: "9:16",
      bgMusic: "worship",
      transitions: "crossfade",
      quality: "high",
    },
    fields: [
      { key: "url", label: "Service Video URL", type: "text" },
      { key: "holiday", label: "Holiday", type: "select", options: [
        { value: "christmas", label: "Christmas" },
        { value: "easter", label: "Easter" },
        { value: "pentecost", label: "Pentecost" },
        { value: "good_friday", label: "Good Friday" },
      ]},
      { key: "pastor", label: "Pastor Name", type: "text" },
    ],
  },
];

// Merge Christian templates into main TEMPLATES array
TEMPLATES.push(...CHRISTIAN_TEMPLATES);
